# kubernetes/accounts-rollout.yaml
# This file is an ADVANCED replacement for accounts-deployment.yaml.
# It requires Istio and Argo Rollouts to be installed in the cluster.
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: accounts-rollout
spec:
  replicas: 3
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
      - name: accounts-service
        # IMPORTANT: Replace with your ECR URI
        image: "YOUR_ECR_REPOSITORY_URI:latest"
        ports:
        - containerPort: 8080
  strategy:
    canary:
      # This part requires an Istio VirtualService to be configured for traffic splitting.
      # The name of the VirtualService should be 'accounts-service'.
      istio:
        virtualService:
          name: accounts-service
      steps:
      - setWeight: 20 # Step 1: Send 20% of traffic to the new version
      - pause: {duration: 30s} # Wait for 30 seconds to monitor
      - setWeight: 50 # Step 2: Increase traffic to 50%
      - pause: {duration: 30s} # Wait again
      # The rollout will then automatically be promoted to 100% if not aborted.
